# Generated by Django 4.1.3 on 2022-12-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
