# Generated by Django 4.1.3 on 2022-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code_pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
